/** @format */

import Permissions from "./Permissions";
const Roles = [
	{
		key: "President",
		permissions: Object.values(Permissions),
	},
	{
		key: "Head",
		permissions: [
			Permissions.ApprovePerson,
			Permissions.RejectPerson,
			Permissions.ViewPerson,
			Permissions.ViewUnverifiedPerson,
			Permissions.ViewTeam,
			Permissions.ViewTeamMembers,
			Permissions.CreateTeamsInTask,
			Permissions.EditTeamsInTask,
			Permissions.DeleteTeamsInTask,
			Permissions.ViewTeamsInTask,
			Permissions.CreateEvent,
			Permissions.EditEvent,
			Permissions.DeleteEvent,
			Permissions.ViewEvent,
			Permissions.InviteMembersToEvent,
			Permissions.RemoveMembersFromEvent,
			Permissions.ManageEventGuests,
			Permissions.CreateTask,
			Permissions.EditTask,
			Permissions.DeleteTask,
			Permissions.ViewTask,
			Permissions.UploadFile,
			Permissions.CreateFeeBack,
			Permissions.EditFeedback,
			Permissions.DeleteFeedback,
			Permissions.ViewFeedback,
			Permissions.ViewAttendance,
			// Achievement permissions
			Permissions.CreateAchievement,
			Permissions.EditAchievement,
			Permissions.DeleteAchievement,
			Permissions.ViewAchievement,
			Permissions.AssignAchievement,
		],
	},
	{
		key: "ViceHead",
		permissions: [
			Permissions.ViewPerson,
			Permissions.ViewTeam,
			Permissions.ViewTeamMembers,
			Permissions.CreateTeamsInTask,
			Permissions.EditTeamsInTask,
			Permissions.DeleteTeamsInTask,
			Permissions.ViewTeamsInTask,
			Permissions.CreateEvent,
			Permissions.EditEvent,
			Permissions.DeleteEvent,
			Permissions.ViewEvent,
			Permissions.InviteMembersToEvent,
			Permissions.RemoveMembersFromEvent,
			Permissions.ManageEventGuests,
			Permissions.CreateTask,
			Permissions.EditTask,
			Permissions.DeleteTask,
			Permissions.ViewTask,
			Permissions.UploadFile,
			Permissions.CreateFeeBack,
			Permissions.EditFeedback,
			Permissions.DeleteFeedback,
			Permissions.ViewFeedback,
			Permissions.ViewAttendance,
			// Achievement permissions
			Permissions.ViewAchievement,
			Permissions.AssignAchievement,
		],
	},
	{
		key: "Member",
		permissions: [
			Permissions.ViewPerson,
			Permissions.ViewTeam,
			Permissions.ViewTeamMembers,
			Permissions.ViewEvent,
			Permissions.ViewTask,
			Permissions.UploadFile,
			Permissions.CreateAttendance,
			Permissions.ViewTeamsInTask,
			Permissions.ViewAttendance,
			// Achievement permissions
			Permissions.ViewAchievement,
		],
	},
	{
		key: "HrMember",
		permissions: [
			Permissions.ViewPerson,
			Permissions.ViewTeam,
			Permissions.ViewTeamMembers,
			Permissions.ViewEvent,
			Permissions.ViewTask,
			Permissions.UploadFile,
			Permissions.CreateAttendance,
			Permissions.EditAttendance,
			Permissions.DeleteAttendance,
			Permissions.ViewAttendance,
			Permissions.CreateFeeBack,
			Permissions.EditFeedback,
			Permissions.DeleteFeedback,
			Permissions.ViewFeedback,
			// Achievement permissions
			Permissions.ViewAchievement,
			Permissions.AssignAchievement,
		],
	},
];

export default Roles;
